version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: eslint
    versions:
    - 7.2.0
  - dependency-name: "@types/jest"
    versions:
    - 25.2.3
  - dependency-name: "@types/ember-qunit"
    versions:
    - 3.4.8
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.3
